### ISSUE TITLE
Feedback re: high level API design

### ISSUE THREAD

**Issue by zonical** [roflmuffin/CounterStrikeSharp#12]
Kia ora,
I've been wanting to experiment with some high level helper functions for the C# API, similar in scope to `Utilities.FindAllEntitiesByDesignerName<>` function that I implemented. The thing I would like to have wider input on is the separation between higher level functions like these and functions for specific classes. I was planning on implementing a more cleaner get/set function for entity origins, but the main question is where to place it. Does it belong in the Utilities class? A separate class for entities? Or `CBaseEntity`? Where should we put the divide between more global functions and entity/object specific type things?

I think a good place to start would be to get some ideas for what the community wants to have implemented that could then be sorted into categories for implementation.

**Comment by roflmuffin** [comment]
This is just a braindump of a prospective separation of concerns, there is a lot of functionality in the `API` section which probably needs to be broken down.

**.Framework.Core**
- Entry point for C++ side
- Initialises logger/dependency injection
- Initialises plugin system

**.Framework.Core.Memory**
- `ScriptContext` for Natives
- `InputArgument` for serialising callbacks
- `FunctionReference` for memory allocating callbacks

**.Framework.Core.Natives**
- Code Generated Native Calls (e.g. `GET_CURRENT_TIME`)

**.Framework.PluginSystem**
- Loads Plugins
- Handles Hot Reloading/Plugin Error State
- Registers Internal Console Commands (`css plugins list`, `css plugins load <plugin>`)
	- Does this cause a dependency issue if these are added through `.API` project?

**.API**
- Adds modules for plugins to interact with:
	- Console Commands
	- Console Variables
	- Game Event Listeners
	- Listeners
	- Virtual Functions
	- Timers
	- Server
	- Players

**.Game.Schema**
- Schema Wrapper Calls to Native (i.e. `GetSchemaOffset`)
- Code Generated Schema Objects
- Only the base objects as per the schema JSON
- Separate folder with implementations of generated classes
	- e.g. `CEntityInstance`, `CEntityIdentity`
- Separate models folder with `partial class` extensions on generated objects
  
**.Game.Schema.Extensions**
- Extension on existing generated objects
- Adds virtual functions to Schema classes
	- e.g. `CommitSuicide` virtual function
- Can't add Properties however due to it being a different assembly
