### ISSUE TITLE
Sugestion: Semantic versioning

### ISSUE THREAD

**Issue by abnerfs** [roflmuffin/CounterStrikeSharp#49]
Hey first of all congratulations for the amazing work, it is really exciting to use a modern language like C# to build plugins 🥳.
The [releases](https://github.com/roflmuffin/CounterStrikeSharp/releases) are being generated using simple version numbers like from v12 -> v13, it would be interesting to follow the [semantic versioning specification](https://semver.org/) so it is easier to identify what is changing, for example if it goes from 12.0.0 to 12.0.1 I can tell that it has only bug fixes, but when it moves from 12.0.0 to 13.0.0 I might expect breaking changes, just a suggestion, I can see this is incentivized in the versioning of the plugins by looking at the examples.

**Comment by KillStr3aK** [comment]
There was a discussion about it on discord in the feature requests forum (API Versioning)
We are using these build/artifact numbers for a reason and it is not supposed to change in the future

**Comment by KillStr3aK** [comment]
These are not "versions" like in the semantic version specification, these are artifact numbers (or we can name them build versions) but its not version 1, version2, version N

As the project is in early stage we expect many artifacts, but as the project goes further in the future there will be less pushes and releases and these version numbers will less likely to change multiple times lets say daily.

these artifact numbers lock new features behind them, so it is pretty easy to set the minimum api version for a plugin, as an example you can take a look on the fivem's artifact system aswell.

**Comment by abnerfs** [comment]
Interesting, I will take a look at the discussion in discord to get more context on this, thanks for the answer

**Comment by KillStr3aK** [comment]
Currently this system is equals to 1.0.BUILD.0 in general, I dont think we should change from using 'artifacts' in the future since it is pretty easy to keep on track. Or maybe when we have a major update, lets say .NET 8.x then we could do the same artifact structure just V2 artifact 1 for example (like 2.0.BUILD.0) or not sure, even continuing with artifact seems a good idea to me, the major would change for sure but idk if we should start from build 1 on v2, or the previous v1 build number + 1

anyway, when the time comes it will be discussed
